services:
  test.db:
    volumes:
      - ./.containers/sqlserver:/var/opt/mssql/data
    ports:
      - "5433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password

  redis:
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
